### PR TITLE
Implement bonus point tracking

### PR DESCRIPTION
**Pull request by Genau6502**
Add bonus points

Bonus points count towards the house point total.

Adds "give_bonus_points" and "see_bonus_points" permissions, granted to admins and participants respectively.
Adds a show_bonus_points page, but this is only accessible to people with "give_bonus_points". Participants can still access the update_bonus_point page via links in their edit_person page.

Added relevant bonus point links to the navbar.
Updates the edit_self page to show information about attendance of events and bonus points: showing the same information as edit_person.

image
image
image
image

The import/export feature is not updated with bonus points, this will follow with a rewrite of that feature soon

Todo:

- Fix bug for error on editing the reason for bonus point

### CODE REVIEW

**Comment by BurntNail** [comment]
mostly looks good to me. do you mind if i try to add a configuration option to remove bonus HPs from the frontend?

**Comment by Genau6502** [comment]
> mostly looks good to me. do you mind if i try to add a configuration option to remove bonus HPs from the frontend?
 All fine

**Comment by BurntNail** [comment]
@Genau6502 apologies for the delay i've been horrifically busy

**Comment by BurntNail** [comment]
FYI, the toggle ended up being that you need to have an environment variable called `HIDE_BONUS_POINTS` to hide it.

**Pull request merged**
